import Head from "next/head";
import styled from "styled-components";
import { AddCircle } from "@mui/icons-material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Budget Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <AddCircle />
      </Main>
    </div>
  );
}

const Main = styled.main`
  padding: 0 2rem;
`;
